apiVersion: v1
kind: Namespace
metadata:
  name: datasnokv3
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: datasnokv3-workflows
  namespace: datasnokv3
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: datasnokv3-full-access
  namespace: datasnokv3
rules:
- apiGroups: [""]
  resources: ["*"]
  verbs: ["*"]
- apiGroups: ["extensions"]
  resources: ["*"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: datasnokv3-admin-rolebinding
  namespace: datasnokv3
subjects:
- kind: ServiceAccount
  name: datasnokv3-workflows
roleRef:
  kind: Role
  name: datasnokv3-web-full-access
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: Secret
type: kubernetes.io/service-account-token
metadata:
  name: datasnokv3-workflows
  namespace: datasnokv3
  annotations:
    kubernetes.io/service-account.name: datasnokv3-workflows